### ISSUE TITLE
Atli: How to control your bill / set limits

### ISSUE THREAD

**Issue by bgrenon** [neondatabase/website#1119]
How to manage your bill and set limits
- Set quotas using the API
- User perspective. I don't want runaway costs. Shut me down if I go over. 
- Partner/reseller perspective: I want to set my own usage limits, tier limits for reselling
- Focus on compute costs, logical size limits, not data transfer/written data
- Check usage via the API

**Comment by bgrenon** [comment]
Notes on proposed handling:

- Create a new "Partner's guide" section under "Guides"
   - New page: Partner's guide landing page can recapitulate information from [partner's page](https://neon.tech/partners) into a doc-friendly format
   - Move [OAuth](https://neon.tech/docs/guides/oauth-integration) under this section
   - New page: Manage billing as a reseller. Use API to set quotas, in the context of reselling Neon.
   - Possible new page: guidelines around using API in a partnership context, if those guidelines make sense
- For regular users, add a section to "Manage billing" that shows how setting your max size effectively sets a max spend amount. However, your real spend is going to be much less. Focus on the savings aspect: compare max spend vs likely spend

**Comment by danieltprice** [comment]
Docs added:
https://neon.tech/docs/guides/partner-intro
