### ISSUE TITLE
Suggest adding support email to documention

### ISSUE THREAD

**Issue by vcabbage** [neondatabase/website#1132]
https://neon.tech/docs/introduction/support states:

> Neon Pro Plan and Custom Plan users can open a support ticket from the Neon console. Look for the Support link in the sidebar. It opens the Create Support Ticket modal, where you can describe your issue.

This works when Neon is operating normally, but in the two instances we had cause to open a support ticket the console was down. It would be helpful if some mention of the support @ neon.tech email (which is linked on https://neonstatus.com/) were added to the documentation.

Thanks!

**Comment by danieltprice** [comment]
Thank you for the suggestion. We added the support email to our Support page in the docs:
https://neon.tech/docs/introduction/support#support-email
