### ISSUE TITLE
Update CLI docs based on recent experience setting it up

### ISSUE THREAD

**Issue by bgrenon** [neondatabase/website#1152]
- I used `npm i -g neonctl` to install. Hit a permission error and had to use sudo.  Since the neonctl installs to user/local/bin, it needs root access to install. We might need to mention something about that.
- I used `neonctl auth` to launch the browser authentication. It worked. I didn't get a chance to try the API method.
- I had more difficulty with getting `completion` setup. The script in my terminal did not match the docs: maxc osx has switched to zshell by default instead of bash. I don't know if the completion script has changed to zsh in all cases, or if it prints differently depending on OS. In either case, we should cover it in the docs: either we need to update the instructions, or tell users to follow their terminal instructions over the doc page, if they differ.
- I completed a couple small actions, renamed projects.

**Comment by bgrenon** [comment]
Here is what gets printed to terminal for me. Notice the switch to zsh instead of bash, in both installation lines:
```zsh
#compdef neonctl
###-begin-neonctl-completions-###
#
# yargs command completion script
#
# Installation: neonctl completion >> ~/.zshrc
#    or neonctl completion >> ~/.zprofile on OSX.
#
_neonctl_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" neonctl --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _neonctl_yargs_completions neonctl
###-end-neonctl-completions-###
```

**Comment by danieltprice** [comment]
- I'll leave out the sudo item, assuming a user can figure this out. I don't see it used in other similar documentation. If users run into issues, we can revisit.
- Addressed the completion script issues. Add an admonition, mentioning that the script may differ, use your own.
Thanks, Barry.
