### ISSUE TITLE
Customer Success: Add a short monitoring page explaining what is available now

### ISSUE THREAD

**Issue by bgrenon** [neondatabase/website#1153]
Explain what limited amount of monitoring is available (relevant pg extensions). Possibly mention that more monitoring features are coming.

Reference:
https://wiki.postgresql.org/wiki/Monitoring
https://www.freshpaint.io/blog/a-beginners-guide-to-postgres-performance-monitoring

How to monitor your usage (usage metrics on Dashbard)
Incorporate any content from Anastasia's blog post)
https://neondb.slack.com/archives/C04USJQNLD6/p1679944872189579

We do have a few things to offer for monitoring:
Dashboard metrics
Branch-specific metrics on the branches page
API metrics (all the above via the API)
Billing page in the console for billing metrics
neon_utils for monitoring Autoscaling: https://neon.tech/docs/extensions/neon-utils
We'll have to investigate what's included with Postgres by default
There are some basic Postgres 3rd party monitoring tools out there, but many require superuser or installing an agent. We can comb through these to see if there are any decent ones that don't require special access or installations: https://wiki.postgresql.org/wiki/Monitoring

ZenDesk ticket:
https://neon.zendesk.com/agent/tickets/1815
If you haven't done so, I would recommend installing [pg_stat_statements](https://www.postgresql.org/docs/15/pgstatstatements.html), which provides tracking planning and execution statistics of all SQL executed.
You can use this to look at long running queries:
-- query the 10 longest running queries with more than 500 calls
WITH statements AS (
SELECT * FROM pg_stat_statements pss
JOIN pg_roles pr ON (userid=oid)
WHERE rolname = current_user
)
SELECT calls, 
mean_exec_time, 
query
FROM statements
WHERE calls > 500
AND shared_blks_hit > 0
ORDER BY mean_exec_time DESC
LIMIT 10;
Cache hit ratio --
-- query the 10 longest running queries
WITH statements AS (
SELECT * FROM pg_stat_statements pss
JOIN pg_roles pr ON (userid=oid)
WHERE rolname = current_user
)
SELECT calls, 
shared_blks_hit,
shared_blks_read,
shared_blks_hit/(shared_blks_hit+shared_blks_read)::NUMERIC*100 hit_cache_ratio,
query
FROM statements
WHERE calls > 500
AND shared_blks_hit > 0
ORDER BY calls DESC, hit_cache_ratio ASC
LIMIT 10;
High standard deviation --
-- query the 10 longest running queries
WITH statements AS (
SELECT * FROM pg_stat_statements pss
JOIN pg_roles pr ON (userid=oid)
WHERE rolname = current_user
)
SELECT calls, 
min_exec_time,
max_exec_time, 
mean_exec_time,
stddev_exec_time,
(stddev_exec_time/mean_exec_time) AS coeff_of_variance,
query
FROM statements
WHERE calls > 500
AND shared_blks_hit > 0
ORDER BY mean_exec_time DESC
LIMIT 10;
And lots more -- and it is especially useful when an issue is sporadic because you may not need to setup explicit capture.
If you are interested in looking at this more visually I would recommend taking a look at [pghero](https://github.com/ankane/pghero), an open source project that works well with Neon.
If you are using Docker, it can be a 2 line setup and will leverage those pg_stat_statement tables for deeper insight.
docker pull ankane/pghero
docker run -ti -e DATABASE_URL=$NEON_DB -p 8080:8080 ankane/pghero

**Comment by danieltprice** [comment]
Completed
