### ISSUE TITLE
Can't sign up with my e-mail

### ISSUE THREAD

**Issue by Rrhapsod** [neondatabase/website#1190]
Hi, I can't create a new account with my business e-mail: allamo@institutoallamo.com.br

I get a message "Invalid email address"

**Comment by PlayLikeNeverB4** [comment]
Hey, thanks for pointing this out. It should work now!

**Comment by danieltprice** [comment]
Closing, as this issue is now resolved. If you encounter any further problems, please let us know. Thank you for opening the issue.
