### ISSUE TITLE
Backup, restore, time-travel assist docs & UI copy

### ISSUE THREAD

**Issue by bgrenon** [neondatabase/website#1276]
Backup and restore docs
UI copy & error text
https://neondb.slack.com/archives/C061CC0Q82J/p1701094272609659

Slack discussion about what our backup & retore will look like:
https://neondb.slack.com/archives/C061CC0Q82J/p1701423807423519

"Rewind" naming
https://neondb.slack.com/archives/C026T7K2YP9/p1701687298663669

**Comment by bgrenon** [comment]
This feature may get pushed next week.

I propose a new overall page to capture 'Branch Restore' as an overall feature, which will include these three methods:

- Restore from branch history
- Restore from target branch
- (future) Restore from backup

One question is what does this restore do the existing PITR docs, which are covered right now in a couple places:
- Introduction > Features
- Guide > Neon features > Branching

**Comment by danieltprice** [comment]
Docs completed.
