### ISSUE TITLE
Discord Invite Breaking

### ISSUE THREAD

**Issue by Taiwrash** [neondatabase/website#1407]
## Steps to reproduce
- Click the discord invite link on the footer of the website

## Expected result
- Supposed to get invited to discord server

## Actual result
- Invite invalid
<img width="1440" alt="Screenshot 2024-02-04 at 11 26 15" src="https://github.com/neondatabase/website/assets/49725691/34d641f0-d757-4779-956e-1e5adcc811e3">

## Environment
- Neon Website

## Logs, links
- 
<img width="1440" alt="Screenshot 2024-02-04 at 11 26 08" src="https://github.com/neondatabase/website/assets/49725691/4cad91c0-f917-4644-9459-561f3c934e66">

**Comment by Taiwrash** [comment]
This was a result of browser, I tried it with another browser and it works. I think my Brave browser was the reason of the error. Thanks for triaging this with me. 

@evanshortiss

**Comment by evanshortiss** [comment]
You're welcome, and I appreciate your follow up @Taiwrash !
