### ISSUE TITLE
Document additional PG features that don't work like usual in our cloud offering

### ISSUE THREAD

**Issue by MMeent** [neondatabase/website#146]
Some of which are:

- We lose statistics on restart (specifically, those referenced [here](https://www.postgresql.org/docs/15/monitoring-stats.html))
- Session semantics are not supported across scaling operations, especially in scale-to-0 situations:
    - LISTEN/NOTIFY
    - PREPARE
    - TEMPORARY TABLE
    - ...

**Comment by danieltprice** [comment]
I added content to the file to address the statistics and session context compatibility issues in #147. Please have a look and let me know what you think. 
Thank you!

**Comment by danieltprice** [comment]
Changes merged with #147
