### ISSUE TITLE
In Neon computes deployed on VM shared buffer hit ratio can not be used to determine working set

### ISSUE THREAD

**Issue by Bodobolero** [neondatabase/website#1476]
https://github.com/neondatabase/website/blob/fb7cd3af0e90b74bad8c2ef1166e7798bfdefe20/content/docs/manage/endpoints.md?plain=1#L137

This chapter is not correct for Neon.
In Neon we have a fixed shared buffers (128 MB) on compute deployed to VMs and thus the shared buffers hit ratio will not improve if you increase the number of cpus in the compute.

Instead the LFC size is bigger for bigger computes and the LFC size needs to be adjusted to working set.

See discussion here https://neondb.slack.com/archives/C06LCQ38EAW/p1708931193287489

**Comment by danieltprice** [comment]
Addressed with the release of the neon extension updates.
