### ISSUE TITLE
copy code introduces extra spacing

### ISSUE THREAD

**Issue by rishi-raj-jain** [neondatabase/website#1649]
When I copy any code from Neon's blog, the spacing is broken.

![image](https://github.com/neondatabase/website/assets/46300090/7111ccea-3cb9-4d41-b3e5-49d7144072b5)
![image](https://github.com/neondatabase/website/assets/46300090/6e696aa8-6722-43dd-8fd8-eab2b4a72810)

**Comment by saimonkat** [comment]
Hi @rishi-raj-jain it's fixed with https://github.com/neondatabase/website/pull/1682

**Comment by rishi-raj-jain** [comment]
> Hi @rishi-raj-jain it's fixed with #1682

Awesome!
