### ISSUE TITLE
feature (content): Using Shiki Transformers

### ISSUE THREAD

**Issue by rishi-raj-jain** [neondatabase/website#1690]
Currently, Shiki is integrated into the system (which is awesome), but highlighting a particular line as insertion and deletion with specific colors is missing. It's a good to have.

**Comment by rishi-raj-jain** [comment]
Being addressed in https://github.com/neondatabase/website/pull/1724.

**Comment by rishi-raj-jain** [comment]
- https://github.com/neondatabase/website/pull/1724/files#diff-09b768860037e61d5b8f3b59dffc714d602d84d23886eeb513e520c45aae274d
- https://github.com/neondatabase/website/pull/1724/files#diff-24af49ca5abe8cb68bafd6b913d714250978eec3978bb9fa35a2f9c097eaaf91

**Comment by saimonkat** [comment]
@rishi-raj-jain I also noticed that we need to update our copy button with styles and functionality.

**Styles**

It's good for dark theme
![image](https://github.com/neondatabase/website/assets/22715126/c194a8c9-7576-4af2-8254-0c541f45c07b)

But has a lack of background for light theme
![image](https://github.com/neondatabase/website/assets/22715126/d3dd1922-c993-420f-9ed8-3576381b7b9f)

**Functionality**
According the functionality on original [shiki transformers](https://shiki.matsu.io/packages/transformers#transformers) copy button shouldn't copy removed lines of code

If you want me, I can help you with this, uploading my commit

**Comment by rishi-raj-jain** [comment]
@saimonkat

Appreciate your detailed review.

Yes, it'd be great to have help from you!

**Comment by rishi-raj-jain** [comment]
Would you be open to committing the changes as you suggested earlier as well? I'm happy to as well.

**Comment by saimonkat** [comment]
@rishi-raj-jain ok sure, I'll commit my updates now. 

Copy button would take extra time by the way, but I'll work on this too.

**Comment by rishi-raj-jain** [comment]
Thank you, @saimonkat!

**Comment by rishi-raj-jain** [comment]
Taking a look now!

**Comment by rishi-raj-jain** [comment]
Added a fix, please review @saimonkat.

**Comment by saimonkat** [comment]
@rishi-raj-jain Thanks! I'm not home now, but overall looks like a good fix overall by the code 🔥 I'll review closer when I'm back home

**Comment by saimonkat** [comment]
Hey @rishi-raj-jain your fix looks really good and works good as well, thank you!

I just optimized it a little bit and I think we're ready!

**Comment by rishi-raj-jain** [comment]
@saimonkat Thank you!

I've simplified it even further: https://github.com/neondatabase/website/pull/1724/commits/92f6c2e0e557eca4cbe8db376c54535a8aff4ab7.

Feel free to drop an approving review for it.
