### ISSUE TITLE
AI page error in local development: "TypeError: Cannot read properties of undefined (reading 'splineEvents')"

### ISSUE THREAD

**Issue by ruf-io** [neondatabase/website#1721]
## Steps to reproduce

Run website locally and navigate to https://localhost:3000/ai

## Expected result

Page loads

## Actual result

Error `TypeError: Cannot read properties of undefined (reading 'splineEvents')`

**Comment by saimonkat** [comment]
@ruf-io fixed at https://github.com/neondatabase/website/pull/1735

**Comment by saimonkat** [comment]
fixed at https://github.com/neondatabase/website/pull/1735
