### ISSUE TITLE
Update frontmatter step failing in deployment

### ISSUE THREAD

**Issue by ruf-io** [neondatabase/website#1757]
Investigate what the level of effort to fix is

https://github.com/neondatabase/website/actions/runs/9306810332/job/25616773955

**Comment by saimonkat** [comment]
Hi @ruf-io it has been fixed on the last week with the new Format Markdown action together, by updating a secret key for actions. Now all actions are working.

![image](https://github.com/neondatabase/website/assets/22715126/cc32d582-f981-43ea-8517-260183ccf7e9)

**Comment by danieltprice** [comment]
fixed by PP.
