### ISSUE TITLE
Address Algolia issues

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#184]
1. Clicks in Algolia search results are not being tracked properly 
2. Algolia search results include doc files not included in the TOC. Indices need to be rebuilt, but how do we exclude files from being indexed again?
3. Where can we place draft files so that they do not show up in search results? Can we exclude files or folders in the content directory from being indexed?

**Comment by danieltprice** [comment]
Defining a topic as isDraft exclues it from Algolia search. This addresses all but  "Clicks in Algolia search results are not being tracked properly"

**Comment by bolotskydev** [comment]
p3. resolved in #258
