### ISSUE TITLE
Broken links to Manage Vercel Environment Variables in Vercel.md

### ISSUE THREAD

**Issue by meandavejustice** [neondatabase/website#1842]
## Steps to reproduce
visit https://neon.tech/docs/guides/vercel#manage-vercel-environment-variables

## Expected result
https://neon.tech/docs/guides/vercel#manage-vercel-environment-variables should link to a "Manage Vercel Environment Variables" section

## Actual result
broken link

## Environment
n/a

## Logs, links
- https://neon.tech/docs/guides/vercel#manage-vercel-environment-variables

**Comment by danieltprice** [comment]
Thank you @meandavejustice 
This will be merged shortly.
https://github.com/neondatabase/website/pull/1857
