### ISSUE TITLE
scrolling being disabled on mobile devices

### ISSUE THREAD

**Issue by Sahilm416** [neondatabase/website#1953]
## Steps to reproduce
 1.  Open docs in mobile screen.
 2.  Tap on documentation menu.
 3.  Click **Ask Neon ai**.
 4.  Close the chat.
 5.  Now scrolling doesn't work

## Expected result
The scrolling should be enabled on mobile devices.

## Actual result
The current behavior disables scrolling even on closing the ai chat.

## Link
- [Neon docs](https://neon.tech/docs/introduction)

**Comment by saimonkat** [comment]
@Sahilm416 thank you for your report!

This issue fixed with https://github.com/neondatabase/website/pull/2035
