### ISSUE TITLE
Estuary Flow integration guide

### ISSUE THREAD

**Issue by danthelion** [neondatabase/website#2006]
Hey folks!

I've briefly discussed adding an integration guide for [Estuary Flow](https://estuary.dev/) to the docs page with @ruf-io, I thought I'd create an issue before submitting a PR as I'm not certain about the contribution process. Happy to get started with the guide if I get an 🆗 

Dani

**Comment by danieltprice** [comment]
Hi @danthelion,

When you're ready to start a guide, the easiest way to do it is to fork our [website](https://github.com/neondatabase/website) repo, create a PR, copy an existing guide, and modify as needed. Decodable recently contributed a guide. It might be helpful to reference that PR to see how they did it: https://github.com/neondatabase/website/pull/1913
If you have any questions along the way, need assistance with graphics, or anything else, just let me know!

We also have a contribution guide here that you can reference:
https://neon.tech/docs/community/contribution-guide

**Comment by danthelion** [comment]
Thanks, @danieltprice, that's great context. I'll write up the integration guide based an example!

**Comment by danieltprice** [comment]
Published:
https://neon.tech/docs/guides/logical-replication-estuary-flow
Thank you for the contribution, @danthelion!

**Comment by danthelion** [comment]
Awesome, thanks for the help @danieltprice!!
