### ISSUE TITLE
Fix: Next Page Button on ‘Getting-Started’ Page Redirects to Itself Instead of Next Page

### ISSUE THREAD

**Issue by lemorage** [neondatabase/website#2081]
## Steps to reproduce
1. Navigate to the [1 - Playing with Neon](https://neon.tech/docs/get-started-with-neon/signing-up) page under the tutorial on the website.
2. On the [1 - Playing with Neon](https://neon.tech/docs/get-started-with-neon/signing-up) page, locate and click the "Next Page" button.

## Expected result
Clicking the "Next Page" button should redirect the user to the next intended page in the sequence.

## Actual result
Clicking the "Next Page" button on the "1 - Playing with Neon" page redirects the user back to the same page, instead of moving to the next page. Btw, the same issue exists on [Why-Neon](https://neon.tech/docs/get-started-with-neon/why-neon) page.

## Environment
- **Browser:** (e.g., Chrome, Firefox, Safari)
- **Operating System:** (e.g., Windows 10, macOS, Ubuntu)
- **Device:** (e.g., Desktop, Laptop, Mobile)
- **Version:** (If applicable, include the version of the website or the app)

## Logs, links
- https://neon.tech/docs/get-started-with-neon/why-neon
- https://neon.tech/docs/get-started-with-neon/signing-up
---

**Comment by ruf-io** [comment]
Thanks for identifying this issue, I can replicate!
