### ISSUE TITLE
Add CODEOWNERS file to website repo

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#211]
Hi @bolotskydev, @lnikell, 
cc @stepashka 

Anna suggested adding a CODEOWNERS file to the website repository to ensure that PR reviewers are notified.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

As an example, the cloud repo has this CODEOWNERS file:
https://github.com/neondatabase/cloud/blob/main/.github/CODEOWNERS

I will add myself as a code owner for the /docs so that I am automatically added as a reviewer for changes to files in that directory:

/content/docs/ @danieltprice 

Could I ask you to identify (in this Issue) the directories or files for which you want to be defined as a code owner?

Once everyone has responded, we'll add the CODEOWNERS file.

Thank you!

**Comment by bolotskydev** [comment]
```yaml
/src/ @bolotskydev
*.js @bolotskydev 
*.jsx @bolotskydev 
```

**Comment by danieltprice** [comment]
Would anyone else like to be a mandatory reviewer for any part of the website repo? @klink?
