### ISSUE TITLE
[Documentation] Update Vercel guide

### ISSUE THREAD

**Issue by YanicNeon** [neondatabase/website#2461]
Our [Vercel Guide](https://neon.tech/docs/guides/vercel) doesn't mention that associated environment variables are also deleted during the obsolete branch deletion.
A customer raised a support case to request clarification regarding this point and if we could document this information.

I clarified with engineering that the relevant variables are indeed deleted, see: https://neondb.slack.com/archives/C079RBJ28F6/p1731501620934299

**Comment by danieltprice** [comment]
Added here:
https://neon.tech/docs/guides/vercel-previews-integration#automatic-deletion
