### ISSUE TITLE
Callotu to Neon Authorize in the Postgres RLS page

### ISSUE THREAD

**Issue by davidgomes** [neondatabase/website#2482]
[This page](https://neon.tech/postgresql/postgresql-administration/postgresql-row-level-security) should have a callout to the [Neon Authorize docs page](https://neon.tech/docs/guides/neon-authorize).

The copy could look something like this:

>Are you looking to integrate your Postgres RLS policies with your application's authentication system? [Neon Authorize](https://neon.tech/docs/guides/neon-authorize) is a feature that leverages the open-source [pg_session_jwt](https://github.com/neondatabase/pg_session_jwt) extension to allow you to write RLS policies that map to your app or service's auth.

**Comment by bgrenon** [comment]
https://neon.tech/postgresql/postgresql-administration/postgresql-row-level-security
