### ISSUE TITLE
Docs Portal (re)Design

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#265]
Review the list of items on the Doc Portal (re) Design Notion page and prepare a staging site to share implemented items from the list.
https://www.notion.so/neondatabase/Docs-Portal-re-Design-6dcf5dc760304ab1a6517ce081abb05a

**Comment by stepashka** [comment]
https://www.figma.com/file/6WyZRL33uvZsBewEWxB3Si/Neon-Website-Design?node-id=9115%3A15508

**Comment by stepashka** [comment]
need to provide the the example(s) of the docs portal landing pages

**Comment by stepashka** [comment]
we'll ship the first iteration this week
then WIP will be the dark mode and teh feedback component

**Comment by bolotskydev** [comment]
The first iteration has been shipped yesterday. What to expect from the next one:
- dark more
- feedback component
- polishing

**Comment by stepashka** [comment]
@danieltprice , whenever the next PR is merged let's prepare the feedback and scope for the next iteration?
