### ISSUE TITLE
Local Development as described does not work offline

### ISSUE THREAD

**Issue by mikeohyan** [neondatabase/website#2690]
Following the Local Development guide found here: https://neon.tech/guides/local-development-with-neon#local-postgresql
The suggested configuration does not work in an offline environment as is. It seems that the `local-neon-http-proxy` relies on the the use of the localtest.me DNS (https://readme.localtest.me/).

My fix was to spool up dnsmasq to ensure the domain (and subdomains) could resolve when there was no internet connection.

**Comment by dhanushreddy291** [comment]
@mikeohyan, thanks a lot for raising this issue, we are fixing it in #2692
