### ISSUE TITLE
add privacy policy & terms & conditions

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#277]
@klink please, provide the content and desired slugs

**Comment by bolotskydev** [comment]
cc @stepashka

**Comment by stepashka** [comment]
https://docs.google.com/document/d/1NbMHU8f5H2ET9LBK8Hu9ZRdEIPvVM2Pw/edit?usp=sharing&ouid=116420355656435273629&rtpof=true&sd=true, https://docs.google.com/document/d/1m1uHdW6Rl1PkETIHjnKHOx5aHOC1tHI5/edit?usp=sharing&ouid=116420355656435273629&rtpof=true&sd=true

**Comment by irinaHl** [comment]
@bolotskydev terms are good to publish; for the Privacy Policy. Please wait for my heads-up. 
in the doc you'll see section "LINK" please link URL to privacy policy/terms instead of word [LINK]

**Comment by irinaHl** [comment]
@bolotskydev Terms and Privacy are good to publish? When will you post the docs at the Website? 
I want to review once publish to make sure correct links are used, no typos.

**Comment by irinaHl** [comment]
@stepashka @acervantes23 these are lightweight versions of docs with users. Simulteneously with billing launch, we'll add: 
- Terms that cover pricing, refunds, upgrades, downgrades, taxes and so on
- Cookie Policy and Cookie Banner
- Lis of Sub-processors 
- DPA
- Update Privacy Policy. 
I will engage US and privacy lawyers to assist with this.

**Comment by acervantes23** [comment]
Thanks @irinaHl. I also suggest that we put our MSA online so we can reference the URL in our Order Forms. What do you think?

**Comment by irinaHl** [comment]
Agree, I did the same way with my previous company. 
We also made OF accepted without signature - it speeds up the closing cycle of smaller deals with ACV ˜$5-15k. AEs closed faster b/c there were no delays on a signature from their side.
