### ISSUE TITLE
create visual guidelines for the docs

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#278]
**Define Neon screen capture, image, and diagram styles & process:**

- Notice the rounded edges and shading that Vercel uses for screen captures: [https://vercel.com/docs/concepts/projects/overview](https://vercel.com/docs/concepts/projects/overview)
- Notice the bordering and shading around images. [https://ritza.co/articles/neon-flask/](https://ritza.co/articles/neon-flask/)
- Also, define a style for arrows and callouts (style, weight, color)
- For diagrams, define our style & process. Our blog process involves sending artwork requests to PP: [https://www.notion.so/neondatabase/How-to-Blog-for-Neon-a75e92db1f6a4600a0240e7ac9e04ef9](https://www.notion.so/How-to-Blog-for-Neon-a75e92db1f6a4600a0240e7ac9e04ef9)
        
Consider the following resources:
            - [https://docs.google.com/presentation/d/16BUe_P3Cz7dzJkjBr8AtV7ETstZDOvYPF0tiEEEycHs/edit#slide=id.g1332016fb25_1_1](https://docs.google.com/presentation/d/16BUe_P3Cz7dzJkjBr8AtV7ETstZDOvYPF0tiEEEycHs/edit#slide=id.g1332016fb25_1_1)
            - [https://docs.google.com/presentation/d/1S7jCMvHXIRMelfZxin6q3-091IGEfcLvogDfbhsqCK4/edit#slide=id.g13beed2dab8_1_0](https://docs.google.com/presentation/d/1S7jCMvHXIRMelfZxin6q3-091IGEfcLvogDfbhsqCK4/edit#slide=id.g13beed2dab8_1_0)
            - [https://mermaid-js.github.io/mermaid/#/](https://mermaid-js.github.io/mermaid/#/)
            - [https://github.com/neondatabase/cloud/tree/main/docs/sequencediagrams](https://github.com/neondatabase/cloud/tree/main/docs/sequencediagrams)

**Comment by danieltprice** [comment]
Mostly sorted out. I will take care of the rest. Closing.
