### ISSUE TITLE
Serverless Driver on Cloudflare Developer Week: Add blog and social cover for the Cloudflare blog post

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#294]
Cloudflare's blog with Cloudflare Workers and Neon connecting over websocket. We are asked to respect their design. Can we do that? Here is an example Cloudflare provided https://blog.cloudflare.com/sending-email-from-workers-with-mailchannels/

![Image](https://user-images.githubusercontent.com/13738772/200520229-df9b1294-b443-4e92-aefe-bcc23f8c13e5.png)

**Comment by bolotskydev** [comment]
Delivered in Slack
