### ISSUE TITLE
Serverless Driver on Cloudflare Developer Week: Workers and Neon workflow

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#295]
We'll need a design equivalent for this image please

![Image](https://user-images.githubusercontent.com/13738772/200521029-4343ed04-e132-4ec1-aac1-9e21bba80c05.png)

**Comment by bolotskydev** [comment]
@raoufchebri Here is the [Figma link](https://www.figma.com/file/6WyZRL33uvZsBewEWxB3Si/Neon-Website-Design?node-id=9591%3A17346), and attaching the final image below



![Image](https://user-images.githubusercontent.com/32940211/201109553-5268c7e2-b2a7-43c8-9771-4b57fd932e39.png)
