### ISSUE TITLE
Hash hrefs link to a not found page instead of scrolling down to a section

### ISSUE THREAD

**Issue by theMosaad** [neondatabase/website#299]
## Steps to reproduce
1. go to https://neon.tech/docs/how-to-guides/connectivity-issues/
2. click [#Details](https://neon.tech/docs/how-to-guides/connectivity-issues/Details) or [#Workarounds](https://neon.tech/docs/how-to-guides/connectivity-issues/Workarounds)

## Expected result
Scroll down to the appropriate section e.g. https://neon.tech/docs/how-to-guides/connectivity-issues/#details

## Actual result
It links to a not found page like https://neon.tech/docs/how-to-guides/connectivity-issues/Details/

**Comment by danieltprice** [comment]
Thank you for reporting the issue. Fixed by https://github.com/neondatabase/website/pull/310
