### ISSUE TITLE
Add custom Neon photo for George

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#316]
We need to add George to the blog and the list of Authors.
Is it possible to modify his photo for this?

![Image](https://user-images.githubusercontent.com/13738772/202011713-48e0fb24-29da-48d7-ac72-b84040a1f694.jpg)

**Comment by bolotskydev** [comment]
@raoufchebri

<details>
<summary>Here you go</summary>


![Image](https://user-images.githubusercontent.com/32940211/202492769-a4df2c35-4001-47e1-a9b7-1e08afd4fd49.png)


</details>
