### ISSUE TITLE
Mention that some psql clients may require SNI fiddling

### ISSUE THREAD

**Issue by yeputons** [neondatabase/website#333]
I have some issues using the standard `psql` on Ubuntu 20.04 (`postgresql-client` APT package): https://github.com/neondatabase/cloud/issues/1405

Seems like the issue is fixed by using Ubuntu 22.04. As Ubuntu 20.04 is still supported, I think it may be worth mentioning at https://neon.tech/docs/get-started-with-neon/query-with-psql-editor . E.g. add the following text to both the "Connect with an exported password" and "Connect with a password saved to a file" sections:

> Note that some older `psql` executables (e.g. from Ubuntu 20.04's `postgresql-client` package) are built without SNI support and require a workaround: https://neon.tech/docs/how-to-guides/connectivity-issues/#a-pass-project-id-in-options

**Comment by danieltprice** [comment]
Fixed by https://github.com/neondatabase/website/pull/374
