### ISSUE TITLE
Documentation is not searchable

### ISSUE THREAD

**Issue by yeputons** [neondatabase/website#338]
## Steps to reproduce
Search for `site:neon.tech "Two PostgreSQL database users are created with each Neon project"` with either of: google.com, duckduckgo.com, yandex.com

## Expected result
All three engines return a link to https://neon.tech/docs/reference/glossary/#postgresql-user

## Actual result
Only yandex.com finds the page, Google and DuckDuckGo find nothing:
![image](https://user-images.githubusercontent.com/1297325/202903546-e289ef18-13d1-4e5d-b23c-b2115f06e825.png)

![image](https://user-images.githubusercontent.com/1297325/202903544-f53829fb-f7be-4407-9de8-e2ef245e5d93.png)

![image](https://user-images.githubusercontent.com/1297325/202903574-eac0d41e-5a1e-4125-b808-0acd08b5e42c.png)

## Impact
Some questions are in the documentation, but are not the first thing the user meets, like the `web-access` PostgreSQL user (see https://github.com/neondatabase/cloud/issues/1403). If a user encounters them, it'd be nice for them to be able to look up the answer with a search engine instead of reading all pages on our website. Also, a global search engine is probably more powerful than anything we can roll out ourselves anyway.

**Comment by yeputons** [comment]
Google and DuckDuckGo now work with that specific query. Google/Yandex also work with `site:neon.tech "Neon supports project deployment in several regions"`, but not DuckDuckGo. `site:neon.tech "A Neon project's root branch is created"` still works with Yandex only.

**Comment by danieltprice** [comment]
This appears to have been resolved. For DuckDuckGo, you can use the bangs (!<site_address>) feature for a site-specific search:

![image](https://github.com/neondatabase/website/assets/10074684/d9b3ca2a-bbfc-475c-8821-ab32ca5fc62a)
