### ISSUE TITLE
Finding it hard to read node.js connection documentation

### ISSUE THREAD

**Issue by Harshil-Jani** [neondatabase/website#361]
By default there is no branching available to users. So, someone who wants to try with the bare bones into NeonDB will struggle to find things without branch. If default purpose is not allowing branching then the document should be done in the similar manner. 

I was reading this page https://neon.tech/docs/guides/node/ and found no nothing about branching and was super confused with the variables and the url which I had. 

Let's draft two sections separately or move this particular connection method under the branching topic here https://neon.tech/docs/introduction/branching/#branch-endpoints

Also, Now the  `options` is no longer working as expected. It throws errors when used. But if we remove `options` then it works as expected. 
So URL should be 

`postgres://${process.env.PGUSER}:${process.env.PGPASSWORD}@${process.env.ENDPOINT_ID}/${process.env.PGDATABASE}?sslmode=require`

**Comment by danieltprice** [comment]
Thank you for the issue.
- Branching is now available to all users.
- For general connection instructions, please see: https://neon.tech/docs/connect/connect-from-any-app
- Our node topic has been updated recently: https://neon.tech/docs/guides/node
If you still find the instructions confusing, please let us know and we will revisit.
