### ISSUE TITLE
Add RSS feed to the blog

### ISSUE THREAD

**Issue by m-abdelwahab** [neondatabase/website#381]
Some users are asking for RSS support

**Comment by lnikell** [comment]
Added as a part of Blog redesign. 
Available by the following link: https://neon.tech/blog/rss.xml

Also accessible from a footer:
<img width="1760" alt="screenshot-2023-06-06-11-38-39@2x" src="https://github.com/neondatabase/website/assets/2697570/7af735e3-89c2-4005-ab01-8cfa1b157e38">
