### ISSUE TITLE
Address linter issues

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#392]
It seems that some of the docs content breaks the linter rules. Please, adjust as you see fit

<details>
<summary> screenshot of the report </summary>

![Image](https://user-images.githubusercontent.com/32940211/207048353-d8aa2c9e-670c-403d-aa1a-b85588be1359.png)

</details>

**Comment by danieltprice** [comment]
Thanks @bolotskydev 
https://github.com/neondatabase/website/pull/394

**Comment by danieltprice** [comment]
Fix merged. Thank you!
