### ISSUE TITLE
<ol start> is still starting with 1 on some pages

### ISSUE THREAD

**Issue by yeputons** [neondatabase/website#40]
For example, here is how I see https://neon.tech/docs/quickstart/node/ in Firefox's inspector:

![изображение](https://user-images.githubusercontent.com/1297325/169261726-01446303-fcf8-4a6b-8fa8-75c8af88ad2d.png)

There are three bullet points, but they are numbered 1, 2, 1 again, even though the third one should be 3.

I suspect some CSS is messing with the counter.

**Comment by SilencerWeb** [comment]
Hey @yeputons! Thanks for reporting this issue. The problem was in incorrect tabulation, see more details in this commit — https://github.com/neondatabase/website/commit/3a4d8d5c7dff59d60fb12a124fb13fc48b34a6ab
