### ISSUE TITLE
Apply for Algolia DocSearch

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#411]
To further improve UX and especially DX for Neon users we suggest Neon to apply for [Algolia DocSearch](https://docsearch.algolia.com/) solution. It bears following benefits:
- a dedicated, docs-tuned crawler
- perf improvements
- a modern up-to-date UI components out of the box with all best practices in place
- fully customizable (brand guidelines can be applied)
- 100% free

Neon is [fully eligible](https://docsearch.algolia.com/apply/) for this one.

**Comment by stepashka** [comment]
i have applied for this
FYI, @bolotskydev @denis-pp

**Comment by stepashka** [comment]
I got a response:


Your DocSearch application has been approved!We will send you another update with instructions once we've completed setting up your application. Let us know if you have any other questions.
