### ISSUE TITLE
Landing page for docs

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#412]
Design a landing page for the documentation. 

- Currently, we land on the about page: https://neon.tech/docs/introduction/about/
- Please see Notion for landing page ideas, possible items to include, and copy: https://www.notion.so/neondatabase/Docs-landing-page-d992cb9557b642d590b2221024b5ed21
- Can PP please create a design and place it on Figma for input from the team, as was done for the Branching page?
Thank you!

**Comment by stepashka** [comment]
updated the ETA to the end of this week based on the conversation today,
cc @danieltprice , @bolotskydev

**Comment by stepashka** [comment]
we'll see the design on wednesday
and if this is approved, this can ship as soon as thursday 🤞

**Comment by stepashka** [comment]
we'll see this in preview tomorrow

**Comment by stepashka** [comment]
this shipped? :)
shall we close it or does something remain?

**Comment by danieltprice** [comment]
Done. Thank you!
