### ISSUE TITLE
[Tutorial] Getting started with Neon (First iteration)

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#446]
(prerequisite for this) the lambda docs are done:
https://neon.tech/docs/guides/aws-lambda

tutorial is what we're doing here
- https://github.com/neondatabase/website/pull/462

**Comment by stepashka** [comment]
this is still in review, right, @danieltprice ?

**Comment by stepashka** [comment]
@danieltprice , @raoufchebri , when do we aim to publish, what are the blockers, concerns, if any?

**Comment by danieltprice** [comment]
Published:
https://neon.tech/docs/tutorial/neon-tutorial
