### ISSUE TITLE
update privacy policy & terms & conditions

### ISSUE THREAD

**Issue by acervantes23** [neondatabase/website#455]
@irinaHl to provide updates for:

Terms that cover pricing, refunds, upgrades, downgrades, taxes and so on
Cookie Policy and Cookie Banner
Lis of Sub-processors
DPA
Update Privacy Policy.

@danieltprice to update Glossary to include terms from Terms & Conditions

**Comment by irinaHl** [comment]
I will finalize privacy docs this-next week and we post them as well

**Comment by irinaHl** [comment]
Team, Daniel proofread Terms, please ping me (Better in Slack) once the terms are uploaded. I will proofread them as on the Site - we may need corrections of links; formatting

**Comment by irinaHl** [comment]
Here are list of corrections https://docs.google.com/document/d/1tovjWnOUvawOP5gu7Heo1Blvrd_NQlOmnKBItAQluHI/edit

In general, if I have access to Wordpress/whatsoever used for website - things will be more efficient. some minor things in legal section -  I can modify on my own and notify everyone. I used this way in my previous company, and it worked out. 
cc @stepashka

**Comment by acervantes23** [comment]
@irinaHl are we good to close this one out?

**Comment by irinaHl** [comment]
Sure
