### ISSUE TITLE
Docs: Improve SEO - Phase 1

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#463]
This task is to outline specific steps that we can take to maximize SEO for our site, including the blog and docs, and to implement those steps. For instance, when someone is Googling how to connect to Postgresql, what can we do improve the odds of our content ranking high in search results? 

The migration to Vercel will impact choices and options, but here are a few suggestions form the team for which there may be equivalents post-Gatsby:

- Competitors use subtitles in their docs. Does this help and should we be doing the same? 
- Enable https://json-ld.org/ for our blog posts. See Google docs: [Introduction to structured data markup in Google Search](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data#guidelines)
- Our html is not gzipped, however all other assets are gzipped. This may affect some performance metrics, and Google can decrease our SEO rank because of site speed. At this moment, our speed is good, but some tools have warned about this.

**Comment by vadim2404** [comment]
* use alternative descriptions for images (`alt="some info"`)
* add `robots.txt` with the link to the `sitemap.xml` (#459)
* @danieltprice mentioned gzipped HTML. The HTML size must be less than 33Kb. Ours is 76Kb
* There are `target="_blank"` links without `rel="noopener"` or `rel="noreferrer"` attribute. It's a performance issue as well (when a user opens such a link browser starts sharing the same CPU resources for both websites)
* HSTS header (#458)
* Meta description should be in the range of 150 and 220 characters. We can add more information here.

**Comment by danieltprice** [comment]
Vadim's SEO-related PRs that remain on root after the Vercel migration. Can we apply these to /next?

https://github.com/neondatabase/website/pull/459
https://github.com/neondatabase/website/pull/458
https://github.com/neondatabase/website/pull/457

**Comment by danieltprice** [comment]
Subtitles were implemented. Thank you!

**Comment by stepashka** [comment]
FYI, @jdrumgoole this is a task we had from a while back
could you review this?

**Comment by stepashka** [comment]
unlikely that we will start working on this in April
so we can take this time to clearly define the full scope of work
and then the implementation can happen some time in may (tentatively)

**Comment by jdrumgoole** [comment]
Also review semrush errors

**Comment by denis-pp** [comment]
@jdrumgoole could you send the invite/credentials to Semrush to view the detailed report with links?

**Comment by lnikell** [comment]
Joe provided a report in xls format. [Link to the report.](https://docs.google.com/spreadsheets/d/19tDxBIpjPzuDoX0VYhn1pdD9Xpz1f-5-eXCFwGvJlHc/edit?pli=1#gid=0)

**Comment by danieltprice** [comment]
@jdrumgoole @lnikell Regarding the SEO effort, can we look at the structured data markup (json-ld) suggestion from @vadim2404 (mentioned in the task description above)? Seems fairly straight forward to implement. It's also recommended in the Google search docs. https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data#why

**Comment by lnikell** [comment]
We merged SEO optimisation fixes to production. Here is the list of things that were completed:
- Set a redirect from https://neon.tech/api-reference to https://api-docs.neon.tech/
- Set a redirect from https://neon.tech/api-reference/v2 to https://api-docs.neon.tech/
- Added custom `meta descriptions` for About Us, Blog, Careers, Contact Sales, Privacy Policy, Terms & Conditions and detailed pages of Release notes
- Added missing `meta description` to Release Notes index page
- Fixed duplicates of h1 on Release Notes index pages
- Fixed duplicates of meta titles on Release Notes
- Disabled `prefetch` for links on docs
- Made a migration to new Next.js Metadata API, now we're safe to upgrade to latest versions of Next.js
- Added better cache headers for fonts

Report, but only on 100 crawled pages(needs an upgrade on Semrush)

Before:

![Image](https://github.com/neondatabase/website/assets/2697570/2f9270f1-88e2-491c-ae04-581404071cf0)

After:

![Image](https://github.com/neondatabase/website/assets/2697570/7c56828b-75d2-43ba-ba73-675397cc1de1)


The remaining 2 Errors coming from links to api-docs from sitemap. Will be fixed soon.
