### ISSUE TITLE
Docs: Release notes page enhancements

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#561]
- Colored tags for Console, Storage, Docs, and potentially Serverless categories
- Ability to filter by category
- We will eventually have Storage, Console, Docs releases on the same day. Does our file naming scheme (date as file name) support this? If not, this should be changed to support more than one release notes the same day

**Comment by bolotskydev** [comment]
#591 was merged, and by this we've resolved:
- tag differentiation
- filters

The last piece will be delivered in a separate PR as it requires release notes file name pattern change.
