### ISSUE TITLE
Promote DD sessions on Twitter

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#609]

**Comment by raoufchebri** [comment]
- [ ] https://twitter.com/neondatabase/status/1635651495826964481
- [ ] https://twitter.com/neondatabase/status/1636015646319476736
- [ ] https://twitter.com/neondatabase/status/1636051381114093568
- [ ] https://twitter.com/neondatabase/status/1636384324730904582
- [ ] https://twitter.com/neondatabase/status/1636741176454774784

**Comment by danieltprice** [comment]
Done. Closing.
