### ISSUE TITLE
Social cover Python + Neon

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#633]
We will need a social cover to promote the tutorial below that uses Django and Neon to create an e-commerce app.
https://www.youtube.com/watch?v=qx9nshX9CQQ

We will share the following message on a Twitter:

```
Check out this 4-hour course by @joincfe where you will learn how to build a modern e-commerce application with Django and Neon.
```

The social cover can feature Python and Neon.

**Comment by bolotskydev** [comment]
@raoufchebri https://www.figma.com/file/a6W3R8ZzwS8Y6OgD3gTKMA/Covers?node-id=145%3A152&t=55q4Ef16lwL4iXBL-1
