### ISSUE TITLE
Bonnyshell blog post cover

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/website#637]
We will need a social cover for the blog post is about our partnership with Bonnyshell 
https://www.bunnyshell.com/

Link to the blog post:

https://docs.google.com/document/d/1qzHHDFptVarnYdZpBLEOsTY4Ixwxu399FCOyBwSl2H0/edit?usp=sharing

**Comment by bolotskydev** [comment]
https://www.figma.com/file/a6W3R8ZzwS8Y6OgD3gTKMA/Covers?node-id=134%3A349&t=dVCEdMuTaPXULZpw-1
