### ISSUE TITLE
Docs: Improve code blocks (or provide alternatives)

### ISSUE THREAD

**Issue by stepashka** [neondatabase/website#694]
The text in code blocks is often too long for the page width. For example:

![Image](https://user-images.githubusercontent.com/10074684/231534681-242eb990-57a8-4687-b235-543eaad5dc64.png)

- Provide a horizontal scroll bar at bottom of code block
- Also, in some cases, we would like to see all of the text in a long connection string without scrolling (i.e., allow wrapping) + the ability to bold items that appear in a connection string (such as the -pooler option.) For example, something like this:
`<mark style="background-color: #f0f0f0;">highlighted <b>text</b></mark>`
The above example does not build.

**Comment by stepashka** [comment]
we can also implement the soft wrap for the code blocks

**Comment by bolotskydev** [comment]
Here is the example with wrapping code blocks https://github.com/neondatabase/website/pull/697

**Comment by raoufchebri** [comment]
This is for the docs right? @denis-pp 
Did we change the code blocks for the blogs?

**Comment by denis-pp** [comment]
@raoufchebri, you're right, only for docs

Do we need these changes in blog?

**Comment by bolotskydev** [comment]
Soft wrapping has been enabled for both docs and blog in #697
