### ISSUE TITLE
Docs: Change RNs Catgeory (Storage -> Storage and Compute)

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#714]
Our "Storage" release notes include Compute release notes, which looks odd.
- Change the "Storage" category/label to "Storage and Compute" 
- Update the Release notes filter on the RNs website to provide a "Storage and Compute" button instead of storage
- I think we can leave the "2023-04-27-storage" file naming scheme alone
- Change the label in the Markdown file for all existing "Storage" release notes files to "Storage and Compute"

**Comment by denis-pp** [comment]
The task is done and deployed to production 

![Image](https://github.com/neondatabase/website/assets/131603105/8bfe1aca-b36b-4b91-a586-d090ab0cefc8)
