### ISSUE TITLE
500 Error on Algolia search results for Release Notes

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#758]
Search on "Storage release". The only results or release notes. A 500 error is returned when clicking on one of the search results.

![Image](https://user-images.githubusercontent.com/10074684/238609135-b03f7254-726c-4451-8602-9787fb00ab45.png)

![Image](https://user-images.githubusercontent.com/10074684/238609202-f3861de5-4882-4243-8d08-a430dce030da.png)

**Comment by denis-pp** [comment]
Was fixed by reindexing in Algolia
