### ISSUE TITLE
Mention the default Postgres schema in docs

### ISSUE THREAD

**Issue by yeputons** [neondatabase/website#76]
PostgreSQL has not only databases and tables/relations, but also "schemas". Some people never encounter them and use the default schema called `public`, while some PostgreSQL clients (like Postgrest: https://github.com/neondatabase/neon/issues/1938) require explicitly specifying the schema.

It'd be nice to mention the default schema name (`public`) somewhere in the documentation for generic connection settings, even though it's not Neon-related, strictly speaking.

**Comment by danieltprice** [comment]
Closing. Update pending second and final approval.
