### ISSUE TITLE
Docs: Navigation link issue

### ISSUE THREAD

**Issue by denis-pp** [neondatabase/website#761]
From this page:
https://neon.tech/docs/security/security-overview

Clock the `[Next Neon API]` navigation link at the bottom of the page. It returns a 404. The Neon API link is defined in the sidebar file as a URL to the Readme API docs. I assume this is the reason the navigation breaks here.

**Comment by denis-pp** [comment]
@danieltprice Fixed in #759

**Comment by danieltprice** [comment]
Thank you @denis-pp
