### ISSUE TITLE
Docs: Add Icon with API references to the Docs navigation

### ISSUE THREAD

**Issue by lnikell** [neondatabase/website#763]
API link to this page - https://api-docs.neon.tech/reference/getting-started-with-neon-api is currently quite hidden and not displayed on the navigation at all. 

It would great to get more visibility on that. 

Proposed sollution

![Image](https://github.com/neondatabase/website/assets/2697570/b24fff92-f7ff-474e-af8d-847da84cd55e)

**Comment by k8isdead** [comment]
Here is the [design](https://www.figma.com/file/6WyZRL33uvZsBewEWxB3Si/Neon-Website-Design?type=design&node-id=16969-6962)


![Image](https://github.com/neondatabase/website/assets/48825888/9ec813a1-c6c5-449e-8c4b-948946d7ce84)

**Comment by lnikell** [comment]
Added as a part of this PR https://github.com/neondatabase/website/pull/803


![Image](https://github.com/neondatabase/website/assets/2697570/638db1cb-931b-4486-aa32-19d825942606)
