### ISSUE TITLE
Docs: Update docs introduction layout

### ISSUE THREAD

**Issue by lnikell** [neondatabase/website#764]
Raouf mentioned that the layout on the introduction docs page might need an improvement considering the current content. His concern is that it requires too much scrolling to see all items. 

![Image](https://github.com/neondatabase/website/assets/2697570/21b95004-e8c2-424c-be51-08a53bf30c5b)

As a quick solution we can wrap it up as a 2 columns layout on a desktop(quick example below)

![Image](https://github.com/neondatabase/website/assets/2697570/283dc900-f13d-4207-9327-b82d26cbcfdf)

Might move icon on top of the title(maybe even remove description if it create more noise rather than meaning)

Eg:

![Image](https://github.com/neondatabase/website/assets/2697570/e0f80ad1-4051-44a6-b1aa-8556b0a18b98)

**Comment by Ckbhatia** [comment]
@lnikell I would suggest adding a tooltip with an info icon to see the description.

I am also up if you can assign this to me

**Comment by denis-pp** [comment]
We've also prepared our suggestions, let's pick the best one 

![Image](https://github.com/neondatabase/website/assets/131603105/caab246b-c088-4435-a78d-1187a5d8f051)

**Comment by Ckbhatia** [comment]
@Daniel-ef Do you have Figma file?

**Comment by Daniel-ef** [comment]
I guess another Daniel :) @danieltprice

**Comment by danieltprice** [comment]
Hi @Ckbhatia I prefer option 1. @raoufchebri What's your preference?

**Comment by Ckbhatia** [comment]
I vote for the first one as well

**Comment by raoufchebri** [comment]
The first one has the smallest height. We wanted users to scroll less to get to the Guides. So it is the best option.

Ideally, users can see both the Documentation and (part of the) Guides section when they open the page.

**Comment by danieltprice** [comment]
@Ckbhatia Looks like option 1. Thank you!

**Comment by Ckbhatia** [comment]
@denis-pp Do I need a special permission to push my branch & raise PR?

**Comment by Ckbhatia** [comment]
@k8isdead I have already made this update and want to raise a PR. But, unable to due to some permission issues with this repo.

**Comment by k8isdead** [comment]
@Ckbhatia hi! unfortunately, I don't have the permission to authorize or decline contributions, please refer to @raoufchebri or other members of the Neon team directly if you want to make one

**Comment by k8isdead** [comment]
@raoufchebri @danieltprice hi! updated the layout in #788 and successfully merged into production

**Comment by danieltprice** [comment]
Thank you!
