### ISSUE TITLE
Docs: Add line highlighting in code blocks

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#836]
This is useful when you want to draw attention to a specific part of a code block. Enable highlighting single lines, multiple lines, and ranges.

Single Line: highlight={1}

Multiple Lines: highlight={1,3}

Range of Lines: highlight={1-5}

![Image](https://user-images.githubusercontent.com/10074684/246801976-b646aed0-a657-4595-8386-804df39920b0.png)

**Comment by Ckbhatia** [comment]
@bolotskydev @lnikell  @k8isdead I am picking this. I will raise a PR soon.

**Comment by Ckbhatia** [comment]
Please update me if someone has already made the requested changes and is ready to raise PR.
If not then, I am working on this.

**Comment by k8isdead** [comment]
@Ckbhatia don’t worry, we are already working on this issue

**Comment by k8isdead** [comment]
@danieltprice hi! we have added the line highlighting in the #864 and described the process in docs [README.md](https://github.com/neondatabase/website/tree/main/content/docs#code-blocks). It supports both dark and light themes, here are the screenshots (these examples are not present in production). 


![Image](https://github.com/neondatabase/website/assets/48825888/ba4b591b-0b16-4a39-9d97-05a34863f2f4)



![Image](https://github.com/neondatabase/website/assets/48825888/5a241d3c-beb2-4c67-82b7-373f3f7c0f06)

**Comment by k8isdead** [comment]
cc @m-abdelwahab @raoufchebri

**Comment by Ckbhatia** [comment]
> @danieltprice hi! we have added the line highlighting in the #864 and described the process in docs [README.md](https://github.com/neondatabase/website/tree/main/content/docs#code-blocks). It supports both dark and light themes, here are the screenshots (these examples are not present in production).
> 
> ![Image](https://user-images.githubusercontent.com/48825888/251721873-ba4b591b-0b16-4a39-9d97-05a34863f2f4.png)
> 
> ![Image](https://user-images.githubusercontent.com/48825888/251721898-5a241d3c-beb2-4c67-82b7-373f3f7c0f06.png)

It's beautiful!
