### ISSUE TITLE
New branch password disappears when revealed

### ISSUE THREAD

**Issue by danieltprice** [neondatabase/website#908]
## Steps to reproduce

When you create a new branch, the Connection Details dialog includes a "covered" password. When you reveal the password, it disappears. When you copy the connection string, the password is not included either.

https://github.com/neondatabase/website/assets/10074684/311d0166-2ce1-4920-87ef-a054bbfad1d1

**Comment by PlayLikeNeverB4** [comment]
Wrong repo? Also, this is a duplicate of https://github.com/neondatabase/cloud/issues/6021
