### ISSUE TITLE
Fix dead link /docs/api/about/

### ISSUE THREAD

**Issue by dein-ding** [neondatabase/website#96]
When you click on '[Neon API](https://neon.tech/docs/api/about/)' in the onboarding section of the console, a dead link shows up.
![image](https://user-images.githubusercontent.com/84234327/181095475-91dca3de-41c0-49b8-b066-049784da91a8.png)

I know it's all not publicly available yet, but I thought it might still help.

**Comment by stepashka** [comment]
i think we've fixed this, @danieltprice , could you confirm?

**Comment by danieltprice** [comment]
Confirmed. The broken Neon API link is fixed.
